# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Generate ULID
#'
#' [ULIDgenerate()] generates a new []Universally Unique Lexicographically
#' Sortable Identifier](https://github.com/ulid/spec).
#'
#' @md
#' @param n number of id's to generate (default = `1`)
#' @export
#' @examples
#' ULIDgenerate()
ULIDgenerate <- function(n = 1L) {
    .Call(`_ulid_ULIDgenerate`, n)
}

